version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links: 
      - postgres:postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  server-registry:
    build: ../server-registry
    ports:
      - "8761:8761"
    tty:
      true
    restart:
      unless-stopped
  rest-producer:
    build: ../rest-producer
    ports:
      - "8098:8098"
    environment:
       - REGISTRY_HOST=server-registry
       - DB_HOST=postgres
    tty:
      true
    restart:
      unless-stopped
  rest-consumer:
    build: ../rest-consumer
    ports:
      - "8082:8082"
    environment:
       - REGISTRY_HOST=server-registry
    tty:
      true
    restart:
      unless-stopped