version: '3.3'
services:
  server-registry:
    build: ../server-registry
    ports:
      - "8761:8761"
    tty:
      true
    restart:
      unless-stopped
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
  rest-producer-1:
    build: ../rest-producer
    ports:
      - "8098:8098"
    environment:
       - SERVER_PORT=8098
       - REGISTRY_HOST=server-registry
       - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?user=postgres&password=postgres&createDatabaseIfNotExist=true
       - SPRING_DATASOURCE_USER=postgres
       - SPRING_DATASOURCE_PASSWORD=postgres
       - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres
      - server-registry
    tty:
      true
    restart:
      unless-stopped
  rest-producer-2:
    build: ../rest-producer
    ports:
      - "8099:8099"
    environment:
       - SERVER_PORT=8099
       - REGISTRY_HOST=server-registry
       - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?user=postgres&password=postgres&createDatabaseIfNotExist=true
       - SPRING_DATASOURCE_USER=postgres
       - SPRING_DATASOURCE_PASSWORD=postgres
       - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres
      - server-registry
    tty:
      true
    restart:
      unless-stopped
  rest-consumer:
    build: ../rest-consumer
    ports:
      - "8082:8082"
    environment:
       - REGISTRY_HOST=server-registry
    tty:
      true
    restart:
      unless-stopped